[project]
name = "sc2ts"
description = "Infer ARGs for SARS-Cov2 in tskit format"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Jerome Kelleher", email = "jerome.kelleher@bdi.ox.ac.uk"},
]
requires-python = ">=3.9"
dependencies = [
  "tsinfer==0.3.3", # https://github.com/jeromekelleher/sc2ts/issues/201
  "pyfaidx",
  "tskit>=0.5.3",
  "tszip",
  "pandas",
  "numba",
  "tqdm",
  "scipy",
  "click",
  "zarr<2.18",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "msprime",
  "pytest",
  "pytest-coverage",
]
analysis = [
  "matplotlib",
  "scikit-learn",
  "pandas",
  "IPython",
  "networkx",
]

[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["sc2ts"]

[tool.setuptools_scm]
write_to = "sc2ts/_version.py"
